Issue 63
dunlapww/viewing_party pull request #88
Opened 2020-12-09 08:39 UTC by GeorgieGirl24

closes #63 
closes #64 
close #65 
Remove: 
  * MovieServiceController
  * TopResults.rb
  * Cast.rb

Add:
  * MovieFacade.rb
  * SearchFacade.rb
  * CastMember.rb
  * MovieDetail.rb
  * Review.rb
  * SearchService.rb

Currently the Controllers make calls on the Facades to make instance variables that can be called in the View. The Facades all create and object/collection of objects. Thus, the return value is a PORO or a collection of PORO's.

There are tests for both Facades, both Services, and all three of the PORO's
The tests have all been updated to reflect this refactor.
All tests are passing.

Please let me know if you have any questions and I will totally explain more!

2020-12-09 14:55 UTC, dunlapww approved these changes
Wow, this is some great work.  thanks George!

2020-12-09 14:55 UTC, dunlapww commented on spec/services/movie_service_spec.rb
> +          expect(results[:vote_average]).to be_a(Integer).or be_a Float
Nice! I was unsuccessfully trying to find this integer or float syntax last night

2020-12-09 17:59 UTC, katemorris requested changes
Please let me know questions!

2020-12-09 17:59 UTC, katemorris commented on app/facades/movie_facade.rb
> +    results[:cast].map do |movie_detail|
For clarity purposes make this cast_member maybe? Since it's that cast member's info not the movies

2020-12-09 17:59 UTC, katemorris commented on app/facades/movie_facade.rb
> +    results[:results].map do |movie_detail|
Same idea here, make the |movie_detail| on this line |review| for clarity purposes

2020-12-09 17:59 UTC, katemorris commented on app/poros/cast_member.rb
> +              :picture,
I don't think we need all of these pieces of info. I think it's just name and character? I am wondering if we should store anything but name and character since we won't need that info anywhere on our site yet. And if we need it later, we can change the model to add it in. Thoughts?

2020-12-09 17:59 UTC, katemorris commented on app/poros/movie_detail.rb
> +    @genres = movie_data[:genres]
Is anything else needing to be done here since genres has nested data? I am not sure but remember that in the back of my head.

2020-12-09 17:59 UTC, katemorris commented on app/poros/movie_detail.rb
> +    @movie_id = movie_data[:id]
Does this need to be uuid? Maybe not, I haven't gotten to the controller yet :P So if not, no worries!

2020-12-09 17:59 UTC, katemorris commented on app/poros/review.rb
> +              :review_id,
same here as with the movie data, is there anything we don't use here? I think we use most of it, but not the review_id and URL?

2020-12-09 17:59 UTC, katemorris commented on app/services/search_service.rb
> +  def self.connection
Can you make all the methods below the output method (self.search) private?

2020-12-09 17:59 UTC, katemorris commented on app/services/search_service.rb
> +  def self.consolidate_results(search_terms)
Where is this called? I think this might be what self.search should call?

2020-12-09 17:59 UTC, katemorris commented on db/schema.rb
> +    # t.bigint 'friend_id'
Potentially remove these comments unless we want to go down this path?

2020-12-09 17:59 UTC, katemorris commented on spec/features/movies/show_spec.rb
> +        review = reviews.second
This whole test is awesome!

2020-12-09 17:59 UTC, katemorris commented on spec/features/search/show_spec.rb
> +        expect(page).to have_css('.movie', count: 20)
I think this test will need to revert back to 40 once you call consolidate results in a file comment I made prior. WE are expecting there to be 40 results and there should be based on the original card.

2020-12-09 17:59 UTC, katemorris commented on spec/features/search/show_spec.rb
> +        expect(page).to have_css(".movie", count: 20)
This should be 22, same issue as below with the 40 results.

2020-12-09 17:59 UTC, katemorris commented on spec/services/movie_service_spec.rb
> +    describe '#cast_data' do
I think this is duplicated from above.

2020-12-10 00:35 UTC, katemorris approved these changes

2020-12-10 00:36 UTC, merged